name       : kwalletmanager
version    : 22.04.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kwalletmanager-22.04.0.tar.xz : d33824ae0abc7972fed9d7dad6acea9f67e7274ee5b15c0bb1df72b1a24aec17
homepage   : https://apps.kde.org/kwalletmanager5/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
optimize   : lto
builddeps  :
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
