name       : kwalletmanager
version    : 20.12.2
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kwalletmanager-20.12.2.tar.xz : 3c76f5c4a62b8ad1cab6532537120e5b4a4dca936b68d3a97ef10283ce1d9d0a
homepage   : https://kde.org/applications/system/org.kde.kwalletmanager
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
optimize   : lto
builddeps  :
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
