name       : kwalletmanager
version    : 20.04.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kwalletmanager-20.04.0.tar.xz : 2a3e6ddd6a076413904ba41535b207313233c0d045abe6b4c27f98d44ee60b14
homepage   : https://kde.org/applications/system/org.kde.kwalletmanager
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
