name       : kwalletmanager
version    : 19.12.3
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kwalletmanager-19.12.3.tar.xz : 247c7f80a54babd21a13e6b9386370b72ec12bdf928c08a7e8a647ccca53e393
homepage   : https://kde.org/applications/system/org.kde.kwalletmanager
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
