name       : kwalletmanager
version    : 17.12.2
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kwalletmanager-17.12.2.tar.xz : 7b7e44a455bf15beca450ff65d52492369c9e4dd10a62c916888777850a50d2b
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
