name       : kwalletmanager
version    : 21.08.3
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kwalletmanager-21.08.3.tar.xz : 582a73846787da55bd9c797d1afd07b65419ac7a6c634749bbd19d305a057831
homepage   : https://apps.kde.org/kwalletmanager5/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
optimize   : lto
builddeps  :
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
