name       : kwalletmanager
version    : 20.12.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kwalletmanager-20.12.1.tar.xz : 72ab9cd2a53b9cc7db144b712ef18d81b23de3ff6b05d92f961b9bff65174f5b
homepage   : https://kde.org/applications/system/org.kde.kwalletmanager
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
