name       : kwalletmanager
version    : 21.04.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/kwalletmanager-21.04.0.tar.xz : 7323e7d548bec44ba53e77bf4e482024644529f25d2b339244bc4d6079eb07e6
homepage   : https://kde.org/applications/system/org.kde.kwalletmanager
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : KWallet Management Tool
description: |
    KWalletManager is a tool to manage the passwords on your system. By using the KDE wallet subsystem it not only allows you to keep your own secrets but also to access and manage the passwords of every application that integrates with the wallet.
optimize   : lto
builddeps  :
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwallet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
